import type { editor } from 'monaco-editor';

export const mocha: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'string', foreground: 'a6e3a1' },
    { token: 'number', foreground: 'fab387' },
    { token: 'keyword', foreground: 'cba6f7' },
    { token: 'type', foreground: 'f9e2af' },
    { token: 'class', foreground: 'f9e2af' },
    { token: 'function', foreground: '89b4fa' },
    { token: 'variable', foreground: 'cdd6f4' },
    { token: 'constant', foreground: 'fab387' },
    { token: 'operator', foreground: '89dceb' },
    { token: 'delimiter', foreground: '9399b2' },
    { token: 'tag', foreground: 'cba6f7' },
  ],
  colors: {
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editorCursor.foreground': '#f5e0dc',
    'editor.lineHighlightBackground': '#313244',
    'editor.selectionBackground': '#585b7066',
    'editor.inactiveSelectionBackground': '#585b7044',
    'editorWidget.background': '#181825',
    'editorWidget.border': '#45475a',
    'editorHoverWidget.background': '#181825',
    'editorHoverWidget.border': '#45475a',
    'editorSuggestWidget.background': '#181825',
    'editorSuggestWidget.border': '#45475a',
    'editorSuggestWidget.selectedBackground': '#313244',
    'editorSuggestWidget.highlightForeground': '#cba6f7',
    'editorIndentGuide.background': '#313244',
    'editorIndentGuide.activeBackground': '#45475a',
    'editorLineNumber.foreground': '#6c7086',
    'editorLineNumber.activeForeground': '#cba6f7',
  },
};

export const latte: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '9ca0b0', fontStyle: 'italic' },
    { token: 'string', foreground: '40a02b' },
    { token: 'number', foreground: 'fe640b' },
    { token: 'keyword', foreground: '8839ef' },
    { token: 'type', foreground: 'df8e1d' },
    { token: 'class', foreground: 'df8e1d' },
    { token: 'function', foreground: '1e66f5' },
    { token: 'variable', foreground: '4c4f69' },
    { token: 'constant', foreground: 'fe640b' },
    { token: 'operator', foreground: '04a5e5' },
    { token: 'delimiter', foreground: '7c7f93' },
    { token: 'tag', foreground: '8839ef' },
  ],
  colors: {
    'editor.background': '#eff1f5',
    'editor.foreground': '#4c4f69',
    'editorCursor.foreground': '#dc8a78',
    'editor.lineHighlightBackground': '#ccd0da',
    'editor.selectionBackground': '#acb0be66',
    'editor.inactiveSelectionBackground': '#acb0be44',
    'editorWidget.background': '#e6e9ef',
    'editorWidget.border': '#bcc0cc',
    'editorHoverWidget.background': '#e6e9ef',
    'editorHoverWidget.border': '#bcc0cc',
    'editorSuggestWidget.background': '#e6e9ef',
    'editorSuggestWidget.border': '#bcc0cc',
    'editorSuggestWidget.selectedBackground': '#ccd0da',
    'editorSuggestWidget.highlightForeground': '#8839ef',
    'editorIndentGuide.background': '#ccd0da',
    'editorIndentGuide.activeBackground': '#bcc0cc',
    'editorLineNumber.foreground': '#9ca0b0',
    'editorLineNumber.activeForeground': '#8839ef',
  },
};

export const githubDark: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'ff7b72' },
    { token: 'string', foreground: 'a5d6ff' },
    { token: 'number', foreground: 'd2a8ff' },
    { token: 'type', foreground: 'ffa657' },
    { token: 'class', foreground: 'ffa657' },
    { token: 'function', foreground: 'd2a8ff' },
    { token: 'variable', foreground: 'c9d1d9' },
    { token: 'constant', foreground: '79c0ff' },
    { token: 'operator', foreground: '79c0ff' },
  ],
  colors: {
    'editor.background': '#0d1117',
    'editor.foreground': '#c9d1d9',
    'editor.lineHighlightBackground': '#161b22',
    'editor.selectionBackground': '#58a6ff33',
    'editorLineNumber.foreground': '#484f58',
    'editorLineNumber.activeForeground': '#c9d1d9',
  },
};

export const githubLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'cf222e' },
    { token: 'string', foreground: '0a3069' },
    { token: 'number', foreground: '0550ae' },
    { token: 'type', foreground: '953800' },
    { token: 'class', foreground: '953800' },
    { token: 'function', foreground: '8250df' },
    { token: 'variable', foreground: '24292f' },
    { token: 'constant', foreground: '0550ae' },
    { token: 'operator', foreground: '0550ae' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24292f',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editor.selectionBackground': '#add6ff66',
    'editorLineNumber.foreground': '#8c959f',
    'editorLineNumber.activeForeground': '#24292f',
  },
};

export const monokai: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'f92672' },
    { token: 'string', foreground: 'e6db74' },
    { token: 'number', foreground: 'ae81ff' },
    { token: 'type', foreground: '66d9ef', fontStyle: 'italic' },
    { token: 'class', foreground: 'a6e22e' },
    { token: 'function', foreground: 'a6e22e' },
    { token: 'variable', foreground: 'f8f8f2' },
    { token: 'constant', foreground: 'ae81ff' },
    { token: 'operator', foreground: 'f92672' },
  ],
  colors: {
    'editor.background': '#272822',
    'editor.foreground': '#f8f8f2',
    'editor.lineHighlightBackground': '#3e3d32',
    'editor.selectionBackground': '#49483e',
    'editorLineNumber.foreground': '#90908a',
    'editorLineNumber.activeForeground': '#f8f8f2',
  },
};

export const shikiDark: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6a737d', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'd73a49' },
    { token: 'string', foreground: '032f62' },
    { token: 'number', foreground: '005cc5' },
    { token: 'type', foreground: '6f42c1' },
    { token: 'class', foreground: '6f42c1' },
    { token: 'function', foreground: '6f42c1' },
    { token: 'variable', foreground: 'e1e4e8' },
    { token: 'constant', foreground: '005cc5' },
    { token: 'operator', foreground: 'd73a49' },
  ],
  colors: {
    'editor.background': '#24292e',
    'editor.foreground': '#e1e4e8',
    'editor.lineHighlightBackground': '#2b3036',
    'editor.selectionBackground': '#3392FF44',
    'editorLineNumber.foreground': '#444d56',
    'editorLineNumber.activeForeground': '#e1e4e8',
  },
};

export const shikiLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6a737d', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'd73a49' },
    { token: 'string', foreground: '032f62' },
    { token: 'number', foreground: '005cc5' },
    { token: 'type', foreground: '6f42c1' },
    { token: 'class', foreground: '6f42c1' },
    { token: 'function', foreground: '6f42c1' },
    { token: 'variable', foreground: '24292e' },
    { token: 'constant', foreground: '005cc5' },
    { token: 'operator', foreground: 'd73a49' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24292e',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editor.selectionBackground': '#0366d625',
    'editorLineNumber.foreground': '#1b1f234d',
    'editorLineNumber.activeForeground': '#24292e',
  },
};

export const shadesOfPurple: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: 'b362ff', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'ff9d00' },
    { token: 'string', foreground: 'a5ff90' },
    { token: 'number', foreground: 'ff628c' },
    { token: 'type', foreground: '9effff' },
    { token: 'class', foreground: '9effff' },
    { token: 'function', foreground: 'fad000' },
    { token: 'variable', foreground: '9effff' },
    { token: 'constant', foreground: 'ff628c' },
    { token: 'operator', foreground: 'ff9d00' },
  ],
  colors: {
    'editor.background': '#2d2b55',
    'editor.foreground': '#a599e9',
    'editor.lineHighlightBackground': '#3b3969',
    'editor.selectionBackground': '#b362ff88',
    'editorLineNumber.foreground': '#a599e9',
    'editorLineNumber.activeForeground': '#fad000',
    'editorIndentGuide.background': '#a599e94d',
    'editorIndentGuide.activeBackground': '#a599e999',
  },
};
