import * as TS from 'typescript';

globalThis.onmessage = async (messageEvent: MessageEvent) => {
  const { id, type, payload } = messageEvent.data;
  try {
    let result: any;

    switch (type) {
      case 'INIT': {
        result = true;
        break;
      }

      case 'VALIDATE_CONFIG': {
        const { tsconfig } = payload;
        const parsed = TS.parseConfigFileTextToJson('tsconfig.json', tsconfig);
        if (parsed.error) {
          result = {
            valid: false,
            error: TS.flattenDiagnosticMessageText(
              parsed.error.messageText,
              '\n',
            ),
          };
        } else {
          result = { valid: true };
        }
        break;
      }

      case 'COMPILE': {
        const lines = payload.code.split('\n');
        const dtsLines = lines.filter((l) => {
          const t = l.trim();
          return (
            t.startsWith('export ') ||
            t.startsWith('interface ') ||
            t.startsWith('type ') ||
            t.startsWith('declare ')
          );
        });

        result = {
          js: '// JS Preview generated by worker',
          dts: dtsLines.join('\n') || '// No declarations found',
        };
        break;
      }

      case 'DETECT_IMPORTS': {
        const sourceFile = TS.createSourceFile(
          'temp.ts',
          payload.code,
          TS.ScriptTarget.Latest,
          true,
        );
        const imports = new Set<string>();
        const visit = (node: TS.Node) => {
          if (
            TS.isImportDeclaration(node) &&
            TS.isStringLiteral(node.moduleSpecifier)
          ) {
            const m = node.moduleSpecifier.text;
            if (!m.startsWith('.') && !m.startsWith('/')) {
              const parts = m.split('/');
              imports.add(
                m.startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0],
              );
            }
          }
          TS.forEachChild(node, visit);
        };
        visit(sourceFile);
        result = [...imports];
        break;
      }

      case 'UPDATE_FILE':
      case 'UPDATE_CONFIG':
      case 'UPDATE_EXTRA_LIBS':
        result = true;
        break;

      default:
        throw new Error(`Unknown worker message type: ${type}`);
    }
    self.postMessage({ id, success: true, payload: result });
  } catch (error) {
    console.error(`Worker error [${type}]:`, error);
    self.postMessage({
      id,
      success: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
};
